eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

server:
  port: 8902

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: local   #启动默认local的yml配置
  application:
    name: application-provider   #该模块的名字
    #文件上传设置大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

