eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

server:
  port: 8903

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: local   #???????local??yml????
  application:
    name: application-order   #??????????
    #???????????§³????
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

